### ISSUE TITLE
Separate pages for networks

### ISSUE THREAD

**Issue by payvint** [Dirt-Road-Development/sfuel-station-v1#28]
## Current problem

When you request SFUEL - your wallet topped up at all of the current networks. Which is unnecessary because user will use only one network in 99% cases

## Solution
Create "/calypso", "/europa", ... pages for SFUEL station for only 1 network

Also /"SCHAIN_NAME" should be referred to the /"name" page

**Comment by TheGreatAxios** [comment]
Resolved by #31
