### ISSUE TITLE
Cannot Add sFuel to wallet

### ISSUE THREAD

**Issue by dogutaskiran** [Dirt-Road-Development/sfuel-station-v1#33]
On the fuel station for Chaos, https://sfuel.skale.network/staging/chaos

Upon clicking "Fuel Wallet" spinner is rotating indefinitely and no sFUEL is added to the connected wallet.

**Comment by TheGreatAxios** [comment]
TODOS
---
- [x] Fix Staging Fill UP
- [x] Fix Staging Chaos Chain Fill Up
- [x] If Spinning Wheel Throw Error

Notes
---
- All networks have reproducible infinite spinning on staging when using https://sfuel.dirtroad.dev/staging
- Chaos Chain is the same at https://sfuel.dirtroad.dev/staging/chaos
- Mainnet Chains are OK and functioning properly

Thank you for filing this issue @hasandogu

**Comment by TheGreatAxios** [comment]
Closed by #34
